{
 "title": "SpringBoot Observability Dashboard",
 "tags": [
  "observability",
  "SpringBoot",
  "Prometheus"
 ],
 "panels": [
  {
   "title": "Total Custom Requests",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "custom_requests_total", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Active Users",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "custom_active_users" }
   ]
  },
  {
   "title": "DB Health Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 4 },
   "targets": [
    {
     "url": "http://localhost:9595/actuator/health",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Request Duration (Latency)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(custom_requests_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(custom_requests_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_requests_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99 Latency"
    }
   ]
  }
 ]
}